# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cryptjournal.ui'
#
# Created: Sat Feb 19 09:55:02 2011
#      by: PySide uic UI code generator
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_CryptJournal(object):
    def setupUi(self, CryptJournal):
        CryptJournal.setObjectName("CryptJournal")
        CryptJournal.resize(800, 600)
        self.centralwidget = QtGui.QWidget(CryptJournal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.grpPassphrase = QtGui.QGroupBox(self.centralwidget)
        self.grpPassphrase.setObjectName("grpPassphrase")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.grpPassphrase)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.grpPassphrase)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.linePassphrase = QtGui.QLineEdit(self.grpPassphrase)
        self.linePassphrase.setEchoMode(QtGui.QLineEdit.Password)
        self.linePassphrase.setObjectName("linePassphrase")
        self.gridLayout.addWidget(self.linePassphrase, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.gridLayout_6.addWidget(self.grpPassphrase, 0, 0, 1, 1)
        self.grpJournal = QtGui.QGroupBox(self.centralwidget)
        self.grpJournal.setObjectName("grpJournal")
        self.gridLayout_3 = QtGui.QGridLayout(self.grpJournal)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listEntries = QtGui.QListWidget(self.grpJournal)
        self.listEntries.setObjectName("listEntries")
        self.gridLayout_2.addWidget(self.listEntries, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.grpJournal, 1, 0, 1, 1)
        self.grpEdit = QtGui.QGroupBox(self.centralwidget)
        self.grpEdit.setObjectName("grpEdit")
        self.gridLayout_5 = QtGui.QGridLayout(self.grpEdit)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblData = QtGui.QLabel(self.grpEdit)
        self.lblData.setObjectName("lblData")
        self.gridLayout_4.addWidget(self.lblData, 2, 0, 1, 1)
        self.lblTitle = QtGui.QLabel(self.grpEdit)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayout_4.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.lineTitle = QtGui.QLineEdit(self.grpEdit)
        self.lineTitle.setObjectName("lineTitle")
        self.gridLayout_4.addWidget(self.lineTitle, 1, 0, 1, 1)
        self.textData = QtGui.QPlainTextEdit(self.grpEdit)
        self.textData.setObjectName("textData")
        self.gridLayout_4.addWidget(self.textData, 3, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.grpEdit)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_4.addWidget(self.buttonBox, 4, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.grpEdit, 2, 0, 1, 1)
        self.textEntry = QtGui.QTextBrowser(self.centralwidget)
        self.textEntry.setOpenExternalLinks(True)
        self.textEntry.setOpenLinks(True)
        self.textEntry.setObjectName("textEntry")
        self.gridLayout_6.addWidget(self.textEntry, 0, 1, 3, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        CryptJournal.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(CryptJournal)
        self.toolBar.setObjectName("toolBar")
        CryptJournal.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd = QtGui.QAction(CryptJournal)
        self.actionAdd.setObjectName("actionAdd")
        self.actionDelete = QtGui.QAction(CryptJournal)
        self.actionDelete.setObjectName("actionDelete")
        self.actionEdit = QtGui.QAction(CryptJournal)
        self.actionEdit.setObjectName("actionEdit")
        self.actionHide = QtGui.QAction(CryptJournal)
        self.actionHide.setObjectName("actionHide")

        self.retranslateUi(CryptJournal)
        QtCore.QObject.connect(self.actionHide, QtCore.SIGNAL("triggered()"), self.textEntry.hide)
        QtCore.QMetaObject.connectSlotsByName(CryptJournal)

    def retranslateUi(self, CryptJournal):
        CryptJournal.setWindowTitle(QtGui.QApplication.translate("CryptJournal", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.grpPassphrase.setTitle(QtGui.QApplication.translate("CryptJournal", "Passphrase", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CryptJournal", "Passphrase:", None, QtGui.QApplication.UnicodeUTF8))
        self.grpJournal.setTitle(QtGui.QApplication.translate("CryptJournal", "Journal list", None, QtGui.QApplication.UnicodeUTF8))
        self.grpEdit.setTitle(QtGui.QApplication.translate("CryptJournal", "Edit Post", None, QtGui.QApplication.UnicodeUTF8))
        self.lblData.setText(QtGui.QApplication.translate("CryptJournal", "Data:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTitle.setText(QtGui.QApplication.translate("CryptJournal", "Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("CryptJournal", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd.setText(QtGui.QApplication.translate("CryptJournal", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd.setShortcut(QtGui.QApplication.translate("CryptJournal", "Ctrl+A", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setText(QtGui.QApplication.translate("CryptJournal", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDelete.setShortcut(QtGui.QApplication.translate("CryptJournal", "Ctrl+D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit.setText(QtGui.QApplication.translate("CryptJournal", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEdit.setShortcut(QtGui.QApplication.translate("CryptJournal", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide.setText(QtGui.QApplication.translate("CryptJournal", "Hide", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHide.setShortcut(QtGui.QApplication.translate("CryptJournal", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))

